begin;
set local search_path=extensions,public,private;
select no_plan();
set local role authenticated;
select set_config('request.jwt.claim.sub','90000000-0000-0000-0000-000000000001',true);
select set_config('request.jwt.claim.role','authenticated',true);
select set_config('request.jwt.claims','{"aal":"aal1","app_metadata":{"role":"admin"}}',true);
select ok(not private.is_admin(),'password or email login alone cannot authorize staff');
select is((public.get_staff_access()->>'mfaRequired')::boolean,true,'staff are directed to MFA');
select throws_ok($$select public.admin_list_reports()$$,'42501',null::text,'direct moderation API requires MFA');
select set_config('request.jwt.claims','{"aal":"aal2","app_metadata":{"role":"admin"}}',true);
select ok(private.is_admin(),'current staff with MFA can act');
select lives_ok($$select public.admin_list_reports()$$,'verified staff can load their queue');
reset role;
update auth.users set raw_app_meta_data='{"role":"member"}' where id='90000000-0000-0000-0000-000000000001';
set local role authenticated;
select ok(not private.is_admin(),'removing a staff role immediately invalidates an existing MFA token');
select is(public.get_staff_access(),null::jsonb,'removed staff receive no console identity');
select throws_ok($$select public.admin_list_reports()$$,'42501',null::text,'stale role claims cannot reopen the queue');
select * from finish();
rollback;
