begin;
-- Real synthetic sessions for member JWT fixtures; rows roll back with this test.
insert into auth.sessions(id,user_id) select md5('pgtap-session:'||id::text)::uuid,id from auth.users;
set local search_path=extensions,public,private;
select no_plan();
select ok(not has_table_privilege('authenticated','private.member_subscriptions','update'),'member cannot edit entitlements');
select ok(not has_function_privilege('authenticated','public.finance_save(bigint,jsonb)','execute'),'member cannot edit ledger');
select ok(not has_function_privilege('anon','public.get_my_entitlement()','execute'),'anonymous entitlement read denied');
select ok(not has_function_privilege('authenticated','public.finance_event_context(uuid)','execute'),'financial roster context is service only');
select is((select mode from private.commerce_configuration),'disabled','fresh install disables commerce');
set local role authenticated;
select set_config('request.jwt.claim.sub','10000000-0000-0000-0000-000000000001',true);
select set_config('request.jwt.claims',(coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb||jsonb_build_object('sub','10000000-0000-0000-0000-000000000001','session_id',md5('pgtap-session:10000000-0000-0000-0000-000000000001')::uuid))::text,true);
select is(public.get_my_entitlement()->>'tier','plebbi','default member is Free');
select throws_ok($$select public.set_premium_profile(true,true)$$,'P0001','premium_required','Free cannot enable Premium effects');
select throws_ok($$select public.set_sandbox_tier('plebba_kongur')$$,'42501','sandbox_disabled','cannot enable own sandbox in production');
reset role;
insert into public.albums(id,owner_id,name) values('90000000-0000-0000-0000-000000000001',auth.uid(),'Tier test');
set local role authenticated;
select throws_ok($$insert into public.albums(owner_id,name) values(auth.uid(),'Over limit')$$,'23514','album_limit_reached','Free second album denied');
select lives_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','video')$$,'Free can reserve one video');
select throws_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','video')$$,'23514','album_media_limit_reached','reservation consumes video capacity');
select lives_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','image') from generate_series(1,10)$$,'Free can reserve ten photos');
select throws_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','image')$$,'23514','album_media_limit_reached','eleventh pending photo denied');
select throws_ok($$insert into public.album_items(album_id,owner_id,storage_path,media_type,position,byte_size) values('90000000-0000-0000-0000-000000000001',auth.uid(),auth.uid()::text||'/90000000-0000-0000-0000-000000000001/raw.jpg','image',1,1)$$,'42501','media_inspection_required','direct media insertion cannot skip inspection');
reset role;
select set_config('test.quarantine_path',(select object_path from private.media_uploads where owner_id='10000000-0000-0000-0000-000000000001' and media_type='video' limit 1),true);
set local role authenticated;
select lives_ok($$insert into storage.objects(bucket_id,name,owner_id) values('media-quarantine',current_setting('test.quarantine_path'),auth.uid()::text)$$,'only a reserved raw object may be uploaded');
select is((select count(*) from storage.objects where bucket_id='media-quarantine'),0::bigint,'even the owner cannot view quarantined raw media');
select throws_ok($$insert into storage.objects(bucket_id,name,owner_id) values('media-quarantine',auth.uid()::text||'/unreserved',auth.uid()::text)$$,'42501',null::text,'direct unreserved uploads cannot bypass quotas');
with changed as (update storage.objects set name=auth.uid()::text||'/replacement' where bucket_id='media-quarantine' returning id)
select is((select count(*) from changed),0::bigint,'members cannot replace raw files after inspection');
reset role;
update private.commerce_configuration set mode='sandbox';
set local role authenticated;
select is(public.set_sandbox_tier('flottari_plebbi')->>'tier','flottari_plebbi','isolated sandbox may select Plus');
select lives_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','video')$$,'Plus can reserve its second video');
select throws_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','video')$$,'23514','album_media_limit_reached','Plus third video is denied');
select lives_ok($$insert into public.albums(owner_id,name) select auth.uid(),'Plus album' from generate_series(1,2)$$,'Plus may have three albums');
select throws_ok($$insert into public.albums(owner_id,name) values(auth.uid(),'Fourth')$$,'23514','album_limit_reached','Plus fourth album denied');
select is(public.set_sandbox_tier('plebba_kongur')->>'tier','plebba_kongur','sandbox Premium selected');
select lives_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','image') from generate_series(1,20)$$,'Premium can reserve thirty photos including the ten existing reservations');
select throws_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','image')$$,'23514','album_media_limit_reached','Premium thirty-first photo is denied');
select lives_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','video')$$,'Premium can reserve its third video');
select throws_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','video')$$,'23514','album_media_limit_reached','Premium fourth video is denied');
select lives_ok($$select public.set_premium_profile(true,true)$$,'Premium can opt into its badge and effect');
select lives_ok($$insert into public.albums(owner_id,name) select auth.uid(),'Premium album' from generate_series(1,3)$$,'Premium may have six albums');
select throws_ok($$insert into public.albums(owner_id,name) values(auth.uid(),'Seventh')$$,'23514','album_limit_reached','Premium seventh album denied');
select public.set_sandbox_tier('plebbi');
select is(public.get_premium_profile(auth.uid())->>'badge','false','badge is hidden after downgrade');
select ok(public.export_my_account() ? 'wallet','account export includes own financial data');
select is((select count(*) from public.albums where owner_id=auth.uid()),6::bigint,'downgrade preserves existing albums');
select throws_ok($$select public.reserve_album_upload('90000000-0000-0000-0000-000000000001','image')$$,'P0001','album_downgrade_limit','downgrade blocks additional uploads');
select lives_ok($$select public.delete_album('90000000-0000-0000-0000-000000000001')$$,'downgrade keeps deletion available');
reset role;
set local role service_role;
select ok(public.finance_save(0,'{"environment":"sandbox","members":{},"journal":[{"id":"fund","entries":[{"account":"external:test","amount":-100},{"account":"platform:reserve","amount":100}]}],"balances":{"external:test":-100,"platform:reserve":100}}'::jsonb),'service can commit a balanced sandbox journal');
select ok(not public.finance_save(0,'{"environment":"sandbox","members":{},"journal":[],"balances":{}}'::jsonb),'stale revision cannot overwrite committed funds');
select throws_ok($$select public.finance_save(1,'{"environment":"sandbox","members":{},"journal":[],"balances":{}}'::jsonb)$$,'P0001','ledger_history_immutable','committed journal entries cannot be removed');
select * from finish();
rollback;
