import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, CalendarDays, Coffee, Compass, LockKeyhole, MapPin, MessageCircle, ShieldCheck, Users } from 'lucide-react';
import { PublicSite, publicStyles as s } from '@/components/public-site';
import { getPublicSiteConfig, siteHref, siteLanguage } from '@/lib/public-site/config';

type Props = { searchParams: Promise<{ lang?: string | string[] }> };
export async function generateMetadata({ searchParams }: Props): Promise<Metadata> {
  const en = siteLanguage((await searchParams).lang) === 'en';
  return { title: { absolute: 'Hittumst · ' + (en ? 'Make a connection. Make a plan.' : 'Ný kynni. Nýjar upplifanir.') }, description: en ? 'Nearby connections and Hittingar social meetups in Iceland. For adults, in Icelandic and English.' : 'Kynnstu fólki í nágrenninu og finndu Hittinga á Íslandi. Fyrir fullorðna, á íslensku og ensku.', robots: { index: getPublicSiteConfig().released, follow: true } };
}
export default async function Home({ searchParams }: Props) {
  const language = siteLanguage((await searchParams).lang), en = language === 'en', config = getPublicSiteConfig();
  return <PublicSite language={language} path="/" config={config}><main id="main" className={s.main}>
    <section className={s.hero}>
      <div><span className={s.eyebrow}>{en ? 'Made for connections in Iceland' : 'Ný kynni á Íslandi'}</span><h1>{en ? <>A little hello.<br />A new <em>possibility.</em></> : <>Segðu hæ.<br />Sjáðu hvað <em>gerist.</em></>}</h1><p className={s.intro}>{en ? 'Meet someone nearby. Find a shared interest. Turn a conversation into a coffee, a walk or something more.' : 'Kynnstu einhverjum í nágrenninu. Finndu sameiginlegt áhugamál. Leyfðu samtalinu að verða að kaffi, göngutúr eða einhverju meira.'}</p>
        <div className={s.actions}>{config.released ? <><a className={s.primary} href={config.iosUrl}>App Store <ArrowRight size={18} aria-hidden="true" /></a><a className={s.secondary} href={config.androidUrl}>Google Play <ArrowRight size={18} aria-hidden="true" /></a></> : <a className={s.primary} href="#hittingar">{en ? 'Meet Hittingar' : 'Kynntu þér Hittinga'} <ArrowRight size={18} aria-hidden="true" /></a>}<Link className={s.secondary} href={siteHref('/community', language)}>{en ? 'Our community' : 'Samfélagið okkar'}</Link></div><p className={s.small}>18+ · {en ? 'Icelandic & English' : 'Íslenska og enska'}{!config.released && (en ? ' · Coming soon' : ' · Væntanlegt')}</p>
      </div>
      <div className={s.preview}><div className={s.previewTop}><strong>Hittingar</strong><span>{en ? 'An example' : 'Dæmi'}</span></div><div className={s.eventCard}><div className={s.eventArt}><Coffee aria-hidden="true" /></div><span className={s.eventLabel}>{en ? 'Social · Coffee & conversation' : 'Félagslegt · Kaffi og spjall'}</span><h2>{en ? 'Start with a coffee.' : 'Byrjum á kaffibolla.'}</h2><p className={s.eventMeta}><MapPin size={15} aria-hidden="true" />{en ? 'Central Reykjavík' : 'Miðborg Reykjavíkur'}</p><p className={s.eventMeta}><CalendarDays size={15} aria-hidden="true" />{en ? 'An easy afternoon together' : 'Notaleg síðdegisstund'}</p><div className={s.eventBottom}><span>{en ? 'A shared interest is a start.' : 'Sameiginlegt áhugamál er byrjun.'}</span><Users size={19} aria-hidden="true" /></div></div><p className={s.previewNote}><LockKeyhole size={20} aria-hidden="true" />{en ? 'Choose a public meeting place for a first meetup.' : 'Veldu opinberan stað fyrir fyrstu kynni.'}</p></div>
    </section>
    <section id="hittingar" className={s.section}><h2>{en ? 'New people. Something to do together.' : 'Nýtt fólk. Eitthvað að gera saman.'}</h2><div className={s.features}>
      {[{ Icon: Compass, title: en ? 'Discover nearby' : 'Uppgötvaðu nágrennið', body: en ? 'Find people around you, explore shared interests and decide who you would like to get to know.' : 'Finndu fólk í nágrenninu, skoðaðu sameiginleg áhugamál og veldu hverjum þú vilt kynnast.' }, { Icon: CalendarDays, title: 'Hittingar', body: en ? 'Coffee, walks, community activities and dating meetups. Find an occasion that feels right, or host your own.' : 'Kaffi, göngur, félagsstarf og stefnumót. Finndu tilefni sem hentar þér eða skipuleggðu þinn eigin Hitting.' }, { Icon: MessageCircle, title: en ? 'Keep the conversation going' : 'Haltu samtalinu áfram', body: en ? 'Say hello in a private chat. Use the meetup conversation to coordinate with the people joining you.' : 'Segðu hæ í einkaspjalli. Notaðu spjall Hittingsins til að samræma plön með þátttakendum.' }].map(({ Icon, title, body }) => <article className={s.feature} key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{body}</p></article>)}
    </div></section>
    <section className={`${s.section} ${s.safety}`}><div><span className={s.eyebrow}>{en ? 'Your pace. Your boundaries.' : 'Þinn hraði. Þín mörk.'}</span><h2>{en ? 'Good connections begin with respect.' : 'Góð kynni byrja á virðingu.'}</h2><p>{en ? 'Every person brings their own story. Be clear about what you are looking for, respect a no and let people choose what they share.' : 'Hver manneskja á sína sögu. Vertu skýr um það sem þú leitar að, virtu nei og leyfðu fólki að velja hvað það deilir.'}</p><Link className={s.secondary} href={siteHref('/support', language)}>{en ? 'Safety & support' : 'Öryggi og aðstoð'} <ArrowRight size={17} aria-hidden="true" /></Link></div><ul>{(en ? ['Adults only. Everyone must be 18 or older.', 'Consent comes first, online and when meeting.', 'Block unwanted contact and report concerns.', 'Private sharing cannot prevent someone making a copy.'] : ['Aðeins fullorðnir. Allir verða að vera 18 ára eða eldri.', 'Samþykki skiptir máli, í spjalli og á Hittingum.', 'Lokaðu á óæskileg samskipti og tilkynntu áhyggjuefni.', 'Einkadeiling kemur ekki í veg fyrir að einhver afriti efni.']).map(item => <li key={item}><ShieldCheck aria-hidden="true" /><span>{item}</span></li>)}</ul></section>
  </main></PublicSite>;
}
