import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { PublicSite, publicDocuments, type PublicDocument, publicStyles as s, SupportLink } from '@/components/public-site';
import { getPublicSiteConfig, siteHref, siteLanguage } from '@/lib/public-site/config';

type Props = { params: Promise<{ document: string }>; searchParams: Promise<{ lang?: string | string[] }> };
function documentKey(value: string): PublicDocument { if (!Object.hasOwn(publicDocuments, value)) notFound(); return value as PublicDocument; }
export async function generateMetadata({ params, searchParams }: Props): Promise<Metadata> {
  const key = documentKey((await params).document), en = siteLanguage((await searchParams).lang) === 'en';
  return { title: { absolute: `${publicDocuments[key][en ? 1 : 0]} · Hittumst` }, robots: { index: getPublicSiteConfig().policiesApproved, follow: true } };
}

export default async function PublicDocumentPage({ params, searchParams }: Props) {
  const key = documentKey((await params).document), language = siteLanguage((await searchParams).lang), en = language === 'en';
  const config = getPublicSiteConfig();
  const copy = (is: string, english: string) => en ? english : is;
  const sections: Record<Exclude<PublicDocument, 'privacy' | 'support' | 'delete-account'>, { title: string; paragraphs: string[] }[]> = {
    terms: [
      { title: copy('Hverjir mega nota Hittumst?', 'Who can use Hittumst?'), paragraphs: [copy('Þú verður að vera að minnsta kosti 18 ára. Gefðu réttar upplýsingar um aldur þinn, notaðu eigin aðgang og gættu aðgangsupplýsinga þinna. Ekki búa til nýjan aðgang til að komast hjá lokun.', 'You must be at least 18. Give your correct age, use your own account and protect your sign-in details. Do not create a new account to evade a restriction.')] },
      { title: copy('Efnið þitt og samskipti', 'Your content and interactions'), paragraphs: [copy('Þú heldur réttindum að eigin efni. Með því að hlaða því upp heimilar þú Hittumst að hýsa, vinna og sýna það til að veita þjónustuna í samræmi við deilingarval þitt. Þú þarft réttindi og samþykki þeirra sem birtast í efninu.', 'You keep the rights to your content. Uploading allows Hittumst to host, process and display it to provide the service according to your sharing choices. You need the rights and consent of people shown in it.'), copy('Samfélagsreglur gilda líka í einkaspjalli, albúmum og á Hittingum. Klámfengnar myndir og myndskeið, áreitni, svik og misnotkun eru óheimil.', 'Community standards also apply in private chats, albums and Hittingar. Sexually explicit images and videos, harassment, fraud and exploitation are prohibited.')] },
      { title: copy('Hittingar og gestgjafar', 'Hittingar and hosts'), paragraphs: [copy('Gestgjafar bera ábyrgð á réttum upplýsingum, öruggri framkvæmd og að tilkynna breytingar eða afbókun. Þátttaka í Hittingi er ekki samþykki fyrir rómantískum eða kynferðislegum samskiptum. Ekki birta heimilisfang eða aðgangskóða annars fólks án leyfis.', 'Hosts are responsible for accurate details, responsible arrangements and communicating changes or cancellation. Joining a meetup does not imply consent to romantic or sexual contact. Do not publish someone else’s address or access code without permission.'), copy('Hittumst tryggir ekki hver auðkenni, hegðun eða mæting þátttakenda er. Þú ákveður hvort og hvernig þú hittir aðra. Miðasala og greiðslur eru ekki hluti af þessari útgáfu.', 'Hittumst does not guarantee participants’ identity, conduct or attendance. You decide whether and how to meet others. Ticketing and payments are outside this release.')] },
      { title: copy('Aðgerðir og endurskoðun', 'Enforcement and review'), paragraphs: [copy('Brot geta leitt til þess að efni sé fjarlægt, viðvörunar, takmörkunar eða lokunar aðgangs. Óska má eftir endurskoðun með því að hafa samband við aðstoð og vísa í viðkomandi ákvörðun. Þú getur eytt aðgangi þínum.', 'Violations can lead to content removal, a warning, a restriction or an account ban. You can request review by contacting support and identifying the decision. You can delete your account.'), copy('Breytingar á skilmálum verða birtar með nýrri dagsetningu. Tilkynnt verður um verulegar breytingar áður en þær taka gildi. Lögbundin réttindi þín haldast.', 'Updated terms will carry a new date. Material changes will be communicated before taking effect. Your statutory rights remain.')] },
    ],
    community: [
      { title: copy('Virðing og samþykki', 'Respect and consent'), paragraphs: [copy('Virtu nöfn, sjálfsmynd, mörk og nei annarra. Ekki þrýsta á fólk um myndir, staðsetningu, kynlíf eða fund. Samþykki má draga til baka hvenær sem er.', 'Respect people’s names, identities, boundaries and refusals. Do not pressure anyone for images, location, sex or a meeting. Consent can be withdrawn at any time.')] },
      { title: copy('Það sem á ekki heima hér', 'What does not belong here'), paragraphs: [copy('Óheimilt er að birta klámfengið efni, hótanir, hatursorðræðu, efni án samþykkis, persónuupplýsingar annarra eða efni sem tengist misnotkun barna. Svindl, eftirlíkingar, mansal, þvingun, vændisauglýsingar og óumbeðnar auglýsingar eru bönnuð.', 'Sexually explicit media, threats, hate, non-consensual content, other people’s private information and child exploitation content are prohibited. Scams, impersonation, trafficking, coercion, solicitation of paid sexual services and unsolicited advertising are banned.'), copy('Aðgangur og Hittingar eru aðeins fyrir 18 ára og eldri. Ekki bjóða börnum í appið eða á Hittinga. Viðburðir með klámfengnu þema eru ekki leyfðir.', 'Accounts and Hittingar are for people aged 18 and older. Do not invite children into the app or to its meetups. Sexually explicit event themes are not allowed.')] },
      { title: copy('Hittumst af tillitssemi', 'Meet considerately'), paragraphs: [copy('Veldu opinberan stað fyrir fyrstu kynni, láttu traustan aðila vita af áætlun þinni og hafðu eigin leið heim. Gestgjafar eiga að lýsa stað og aðgengi rétt, virða fjöldamörk og tilkynna breytingar. Farðu ef þér líður óþægilega.', 'Choose a public place for a first meeting, share your plans with someone you trust and arrange your own way home. Hosts should describe the venue and accessibility accurately, respect capacity and communicate changes. Leave if you feel uncomfortable.')] },
      { title: copy('Tilkynntu áhyggjuefni', 'Report a concern'), paragraphs: [copy('Notaðu Tilkynna á prófíl, efni eða Hittingi. Lokaðu á óæskileg samskipti. Ekki endurbirta skaðlegt efni eða reyna að leysa hættulegar aðstæður sjálf/ur. Aðstoð getur skoðað ákvörðun aftur ef þú telur hana ranga.', 'Use Report on a profile, content item or meetup. Block unwanted contact. Do not repost harmful content or try to investigate dangerous situations yourself. Support can review a decision if you believe it is wrong.')] },
    ],
    'child-safety': [
      { title: copy('Börn eiga ekki aðgang að Hittumst', 'Hittumst is for adults'), paragraphs: [copy('Hittumst er fyrir fólk 18 ára og eldra. Kynferðisleg misnotkun og arðrán barna eru með öllu bönnuð. Það nær meðal annars til barnaníðsefnis, tælingar, kynferðislegrar kúgunar og mansals barna.', 'Hittumst is for people aged 18 and older. Child sexual abuse and exploitation are strictly prohibited, including abuse material, grooming, sexual extortion and trafficking of children.')] },
      { title: copy('Hvernig tilkynnir þú?', 'How to report'), paragraphs: [copy('Veldu Tilkynna í appinu ef grunur er um barn undir 18 ára aldri, barnaníðsefni eða hættu fyrir barn. Gefðu upp viðkomandi aðgang eða Hitting og lýstu áhyggjum þínum. Ekki sækja, afrita eða senda áfram efni sem gæti verið ólöglegt.', 'Use Report in the app for a suspected underage account, child abuse material or a child at risk. Identify the account or meetup and describe your concern. Do not download, copy or forward potentially illegal material.')] },
      { title: copy('Viðbrögð við tilkynningu', 'Responding to reports'), paragraphs: [copy('Öryggisteymi metur tilkynningar, takmarkar aðgang að grunsamlegu efni og grípur til viðeigandi aðgerða. Staðfest barnaníðsefni er fjarlægt úr aðgengi. Sönnunargögn eru takmörkuð við heimilað starfsfólk og varðveisla og tilkynningar til yfirvalda fylgja gildandi lögum.', 'The safety team assesses reports, restricts access to suspected content and takes appropriate action. Confirmed child abuse material is removed from access. Evidence is restricted to authorized staff; preservation and reporting to authorities follow applicable law.')] },
    ],
  };
  return <PublicSite language={language} path={`/${key}`} config={config}><main id="main" className={s.document}>
    <Link href={siteHref('/', language)}>← Hittumst</Link><h1>{publicDocuments[key][en ? 1 : 0]}</h1>
    <p className={s.muted}>{config.policiesApproved ? copy(`Gildir frá ${config.policyDate}`, `Effective ${config.policyDate}`) : copy('Drög · Ekki samþykkt til útgáfu', 'Draft · Awaiting release approval')}</p>
    {key === 'privacy' && <>
      <p className={s.lead}>{copy('Þú velur hvað þú deilir. Hér er lýst upplýsingunum sem Hittumst notar og hvernig þú stjórnar þeim.', 'You choose what you share. This notice describes the information Hittumst uses and how you control it.')}</p>
      <section><h2>{copy('Ábyrgð og samband', 'Operator and contact')}</h2><p>{config.operator ?? copy('Nafn rekstraraðila verður staðfest áður en þjónustan opnar.', 'The operator will be identified before the service opens.')}{config.address && ` · ${config.address}`}</p><SupportLink config={config} language={language} /></section>
      <section><h2>{copy('Upplýsingar og tilgangur', 'Information and purpose')}</h2><p>{copy('Aðgangsupplýsingar styðja innskráningu og aldursskilyrði. Prófíll, myndir, myndskeið og skilaboð gera þér kleift að tengjast öðrum. Hittingar nota viðburðalýsingar, þátttöku, staðsetningar og spjall. Tilkynningar, lokanir og aðgerðaskrár styðja öryggi.', 'Account details support sign-in and age eligibility. Profiles, images, videos and messages let you connect with others. Hittingar uses event details, participation, locations and room messages. Reports, blocks and decision records support safety.')}</p><p>{copy('Rekstur aðgangs byggist á samningi; valfrjálsar viðkvæmar prófílupplýsingar á sérstöku samþykki. Öryggisvinnsla byggist á lögmætum hagsmunum og lagaskyldum eftir því sem við á. Nánari mat á vinnslu og heimildum þarf samþykki fyrir prófanir.', 'Account operation relies on contract; optional sensitive profile information requires separate consent. Safety processing relies on legitimate interests and legal duties where applicable. The detailed processing and legal-basis assessment must be approved before the pilot.')}</p></section>
      <section><h2>{copy('Staðsetning og deiling', 'Location and sharing')}</h2><p>{copy('Nálægðarleit sýnir gróft svæði. Opinber staðsetning Hittings er sýnileg í viðburðinum. Vernduð heimilisföng, leiðbeiningar og netfundaraðgangur eru aðeins aðgengileg gjaldgengum þátttakendum á skilgreindum tíma. Veldu aðeins opinbera staðsetningu ef þú hefur leyfi til að birta hana.', 'Nearby discovery shows a coarse area. A Public meetup location is visible with the event. Protected addresses, instructions and online meeting access are available only to eligible participants during the specified window. Publish a location only with permission.')}</p><p>{copy('Móttakendur geta afritað upplýsingar sem þeir sjá. Afturköllun albúmaðgangs stöðvar nýjan aðgang; áður útgefnir hlekkir geta gilt í allt að 60 sekúndur. Hún eyðir ekki afritum hjá öðrum.', 'Recipients can copy information they see. Revoking album access blocks new access; previously issued links can remain valid for up to 60 seconds. Revocation cannot remove copies already made.')}</p></section>
      <section><h2>{copy('Þjónustuaðilar', 'Service providers')}</h2>{!config.policiesApproved && <p className={s.muted}>{copy('Fyrirhuguð þjónusta. Staðfesta þarf samninga, stillingar og flutningsheimildir áður en raunveruleg gögn eru unnin.', 'Planned services. Contracts, configuration and transfer safeguards must be confirmed before processing real data.')}</p>}<table><thead><tr><th>{copy('Aðili', 'Provider')}</th><th>{copy('Tilgangur og gögn', 'Purpose and data')}</th></tr></thead><tbody>{[
        ['Supabase', copy('Aðgangar, gagnagrunnur, miðlar og skilaboð.', 'Accounts, database, media and messaging.')], ['Vercel', copy('Vefur, öryggisvinnsla og bakgrunnsverk.', 'Website, safety operations and background jobs.')], ['Resend', copy('Innskráningar- og þjónustupóstur.', 'Sign-in and transactional email.')], ['MapTiler', copy('Kort og leit að heimilisföngum fyrir Hittinga.', 'Maps and meetup address search.')], ['AWS', copy('Öryggisafrit og sjálfvirkt mat á upphlöðnu efni.', 'Backups and automated upload moderation.')], ['Sentry', copy('Villur og afköst, án innihalds spjalla eða verndaðra staðsetninga.', 'Errors and performance, excluding chat content and protected locations.')], ['Expo / Apple / Google', copy('Afhending almennra tilkynninga og valfrjáls innskráning.', 'Delivery of generic notifications and optional sign-in.')],
      ].map(([provider, purpose]) => <tr key={provider}><td>{provider}</td><td>{purpose}</td></tr>)}</tbody></table><p>{(en ? config.transfersEn : config.transfersIs) ?? copy('Upplýsingar um staðsetningu vinnslu og flutningsvernd bíða samþykktar rekstraraðila.', 'Processing locations and international transfer safeguards await operator approval.')}</p></section>
      <section><h2>{copy('Varðveisla og eyðing', 'Retention and deletion')}</h2><p>{(en ? config.retentionEn : config.retentionIs) ?? copy('Varðveislutímar fyrir aðganga, skilaboð, Hittinga, nákvæmar staðsetningar, aðgangskóða, þátttöku, mætingu, tilkynningar og öryggisgögn bíða samþykktar. Tímafrestir fyrir aðgang að spjalli og staðsetningu eru ekki það sama og eyðing gagna.', 'Retention periods for accounts, messages, meetups, exact locations, access codes, participation, attendance, notifications and safety records await approval. Room and location access deadlines do not mean the underlying records have been erased.')}</p><Link href={siteHref('/delete-account', language)}>{copy('Hvernig eyði ég aðganginum?', 'How do I delete my account?')}</Link></section>
      <section><h2>{copy('Val þitt og réttindi', 'Choices and rights')}</h2><p>{copy('Þú getur óskað eftir aðgangi, leiðréttingu, eyðingu, takmörkun og flutningi gagna, andmælt vinnslu og afturkallað samþykki. Þú getur kvartað til Persónuverndar. Hafðu samband við aðstoð; staðfesta þarf að beiðnin komi frá réttum aðila.', 'You can request access, correction, deletion, restriction and portability, object to processing and withdraw consent. You can complain to Iceland’s Data Protection Authority. Contact support; requests require proportionate identity verification.')}</p><p>{copy('Sjálfvirk yfirferð miðla getur haft rangt fyrir sér. Óskaðu eftir mannlegri endurskoðun ef efni er hafnað. Þessi vefur setur ekki inn auglýsingapixla eða upptökur af vefnotkun.', 'Automated media checks can be wrong. Request human review if content is rejected. This website does not embed advertising pixels or session recordings.')}</p><SupportLink config={config} language={language} subject="Hittumst privacy request" /></section>
    </>}
    {(key === 'terms' || key === 'community' || key === 'child-safety') && sections[key].map(section => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(p => <p key={p}>{p}</p>)}</section>)}
    {key === 'child-safety' && <section><h2>{copy('Tengiliður vegna öryggis barna', 'Child safety contact')}</h2>{config.childSafetyEmail ? <a href={`mailto:${config.childSafetyEmail}`}>{config.childSafetyEmail}</a> : <p>{copy('Vaktað netfang og ábyrgðaraðili verða staðfest áður en prófanir hefjast.', 'A monitored contact and responsible person must be confirmed before the pilot.')}</p>}<p>{copy('Ef barn er í bráðri hættu á Íslandi skaltu hringja í 112.', 'If a child is in immediate danger in Iceland, call 112.')} <a href="https://www.112.is/en">112.is</a></p></section>}
    {key === 'support' && <>
      <p className={s.lead}>{copy('Við hjálpum með aðgang, tilkynningar og Hittinga.', 'Get help with your account, reports and Hittingar.')}</p><SupportLink config={config} language={language} />
      <p>{(en ? config.coverageEn : config.coverageIs) ?? copy('Opnunartímar aðstoðar verða birtir áður en prófanir hefjast.', 'Support hours will be published before the pilot.')}</p>
      <div className={s.notice}>{copy('Hittumst er ekki neyðarþjónusta. Í bráðri hættu á Íslandi: hringdu í 112.', 'Hittumst is not an emergency service. For immediate danger in Iceland, call 112.')} <a href="https://www.112.is/en">112.is</a></div>
      <section><h2>{copy('Tilkynning eða óæskileg samskipti', 'Reporting or unwanted contact')}</h2><p>{copy('Notaðu Tilkynna við viðkomandi prófíl, efni eða Hitting svo málið tengist réttum upplýsingum. Þú getur líka lokað á viðkomandi. Tilkynningar þurfa ekki að innihalda nákvæmt heimilisfang eða afrit af einkamyndum.', 'Use Report on the relevant profile, content or meetup to attach the right context. You can also block the person. Reports do not need an exact address or copies of private images.')}</p></section>
      <section><h2>{copy('Vandamál með Hitting', 'A problem with a meetup')}</h2><p>{copy('Athugaðu stöðu þátttöku og nýjustu tilkynningar. Vernduð staðsetning getur birst síðar og hverfur þegar aðgangur rennur út. Tilkynntu óöruggar eða rangar upplýsingar. Ef þú ert gestgjafi skaltu uppfæra eða aflýsa Hittingi þegar áætlanir breytast.', 'Check your participation status and recent notices. A Protected location may be released later and disappears when access expires. Report unsafe or misleading details. If you are the host, update or cancel the meetup when plans change.')}</p></section>
      <section><h2>{copy('Endurskoðun ákvörðunar', 'Appeal a decision')}</h2><p>{copy('Sendu númer máls eða auðkenni efnis og stutta skýringu á því sem þú telur rangt. Óskaðu eftir mannlegri endurskoðun. Ekki senda lykilorð, aðgangskóða eða ólöglegt efni.', 'Send the case or content identifier and a short explanation of what you believe is wrong. Ask for human review. Do not send passwords, access codes or illegal material.')}</p><SupportLink config={config} language={language} subject="Hittumst decision review" /></section>
      <section><h2>{copy('Aðgangur og persónuvernd', 'Account and privacy')}</h2><p><Link href={siteHref('/delete-account', language)}>{copy('Eyða aðgangi og tengdum gögnum', 'Delete your account and associated data')}</Link></p><p><Link href={siteHref('/privacy', language)}>{copy('Upplýsingar um gögnin þín', 'Information about your data')}</Link></p></section>
    </>}
    {key === 'delete-account' && <>
      <p className={s.lead}>{copy('Þú getur óskað eftir eyðingu Hittumst-aðgangsins í appinu eða með tölvupósti án þess að setja appið upp aftur.', 'You can request deletion of your Hittumst account in the app or by email without reinstalling it.')}</p>
      <section><h2>{copy('Í appinu', 'In the app')}</h2><ol><li>{copy('Opnaðu Stillingar og síðan Persónuvernd.', 'Open Settings, then Privacy.')}</li><li>{copy('Veldu Eyða aðgangi og lestu upplýsingarnar.', 'Choose Delete account and read the explanation.')}</li><li>{copy('Staðfestu eyðinguna.', 'Confirm deletion.')}</li></ol></section>
      <section><h2>{copy('Án aðgangs að appinu', 'Without access to the app')}</h2><p>{copy('Sendu beiðni úr netfanginu sem tengist aðganginum og skrifaðu að þú viljir eyða Hittumst-aðgangi og tengdum gögnum. Aðstoð staðfestir eignarhald áður en beiðnin er framkvæmd. Ekki senda lykilorð eða innskráningarkóða. Ef þú hefur misst aðgang að netfanginu skaltu biðja um aðstoð við staðfestingu.', 'Email from the address linked to your account and state that you want your Hittumst account and associated data deleted. Support verifies ownership before processing the request. Do not send a password or sign-in code. If you lost access to that email, ask for help verifying ownership.')}</p><SupportLink config={config} language={language} subject="Delete my Hittumst account" /></section>
      <section><h2>{copy('Hvað gerist?', 'What happens?')}</h2><p>{copy('Þegar staðfest beiðni er skráð er aðgangur takmarkaður, prófíll falinn og einkadeiling afturkölluð. Framtíðar-Hittingum sem þú hýsir er aflýst og þátttakendur fá almenna tilkynningu. Eyðingarverk fjarlægir tengd aðgangsgögn, miðla og tilkynningatákn.', 'Once a verified request is recorded, account access is restricted, your profile is hidden and private sharing is revoked. Future meetups you host are cancelled and participants receive a generic notice. A deletion job removes associated account data, media and push tokens.')}</p><p>{copy('Sérstök öryggisgögn geta þurft varðveislu vegna mála eða lagaskyldu. Afrit hjá öðrum hverfa ekki. Varðveislutímar og undantekningar eru birt í persónuverndarstefnu; fjarlæging appsins af símanum eyðir ekki aðganginum.', 'Specific safety evidence may need to be retained for cases or legal duties. Copies made by others remain. Retention periods and exceptions appear in the privacy notice; uninstalling the app does not delete your account.')}</p><Link href={siteHref('/privacy', language)}>{copy('Varðveisla og persónuvernd', 'Retention and privacy')}</Link></section>
    </>}
    {(key === 'terms' || key === 'community') && <section><h2>{copy('Þarftu aðstoð?', 'Need help?')}</h2><Link href={siteHref('/support', language)}>{copy('Aðstoð og endurskoðun ákvarðana', 'Support and decision reviews')}</Link></section>}
  </main></PublicSite>;
}
