import type {SupabaseClient} from '@supabase/supabase-js';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {eraseRevenueCatCustomer} from './erasure';
const id='10000000-0000-4000-8000-000000000001',job='10000000-0000-4000-8000-000000000002',claim='10000000-0000-4000-8000-000000000003';
const rpc=vi.fn(),fetcher=vi.fn();const db={rpc} as unknown as SupabaseClient;
const json=(value:unknown)=>new Response(JSON.stringify(value));
beforeEach(()=>{vi.resetAllMocks();vi.stubGlobal('fetch',fetcher);vi.stubEnv('HITTUMST_APP_ENV','production');vi.stubEnv('REVENUECAT_ENVIRONMENT','PRODUCTION');vi.stubEnv('REVENUECAT_PROJECT_ID','projExample');vi.stubEnv('REVENUECAT_ERASURE_KEY','test-secret-key-with-sufficient-length');rpc.mockResolvedValue({data:{state:'ready',required:true,environment:'PRODUCTION'},error:null});});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
describe('RevenueCat erasure',()=>{
 it('waits for in-flight billing leases before any provider action',async()=>{rpc.mockResolvedValue({data:{state:'processing'},error:null});await expect(eraseRevenueCatCustomer(db,id,job,claim)).rejects.toThrow('billing_erasure_pending');expect(fetcher).not.toHaveBeenCalled();});
 it('treats a missing customer as erased without a get-or-create lookup',async()=>{fetcher.mockResolvedValue(new Response('',{status:404}));await eraseRevenueCatCustomer(db,id,job,claim);expect(fetcher).toHaveBeenCalledTimes(1);expect(fetcher.mock.calls[0][0]).toContain('/v2/projects/projExample/customers/');expect(fetcher.mock.calls[0][1]).toMatchObject({method:'GET',redirect:'error'});});
 it('protects aliases belonging to another live app account',async()=>{fetcher.mockResolvedValueOnce(json({id})).mockResolvedValueOnce(json({items:[{id:job}],next_page:null}));rpc.mockResolvedValueOnce({data:{state:'ready',required:true,environment:'PRODUCTION'},error:null}).mockResolvedValueOnce({data:{state:'alias_review_required'},error:null});await expect(eraseRevenueCatCustomer(db,id,job,claim)).rejects.toThrow('billing_erasure_alias_review_required');expect(fetcher.mock.calls.some(call=>call[1].method==='DELETE')).toBe(false);expect(rpc).toHaveBeenLastCalledWith('billing_provider_guard',expect.objectContaining({p_aliases:[id,job]}));});
 it('confirms asynchronous erasure through non-creating V2 GET',async()=>{fetcher.mockResolvedValueOnce(json({id})).mockResolvedValueOnce(json({items:[{id}],next_page:null})).mockResolvedValueOnce(json({id,deleted_at:Date.now()})).mockResolvedValueOnce(new Response('',{status:404}));await eraseRevenueCatCustomer(db,id,job,claim);expect(fetcher.mock.calls.map(call=>call[1].method)).toEqual(['GET','GET','DELETE','GET']);});
 it('leaves the deletion durable when provider acceptance has not finished',async()=>{fetcher.mockResolvedValueOnce(json({id})).mockResolvedValueOnce(json({items:[],next_page:null})).mockResolvedValueOnce(json({id})).mockResolvedValueOnce(json({id,deleted_at:null}));await expect(eraseRevenueCatCustomer(db,id,job,claim)).rejects.toThrow('billing_erasure_provider_pending');});
 it('refuses to erase using a different environment or absent erasure credentials',async()=>{vi.stubEnv('REVENUECAT_ENVIRONMENT','SANDBOX');await expect(eraseRevenueCatCustomer(db,id,job,claim)).rejects.toThrow('billing_erasure_environment_mismatch');vi.stubEnv('REVENUECAT_ENVIRONMENT','PRODUCTION');vi.stubEnv('REVENUECAT_ERASURE_KEY','');await expect(eraseRevenueCatCustomer(db,id,job,claim)).rejects.toThrow('billing_erasure_unavailable');expect(fetcher).not.toHaveBeenCalled();});
 it('does not follow provider-controlled pagination URLs',async()=>{fetcher.mockResolvedValueOnce(json({id})).mockResolvedValueOnce(json({items:[{id:'opaque/id'}],next_page:'https://evil.example'})).mockResolvedValueOnce(json({items:[],next_page:null})).mockResolvedValueOnce(new Response('',{status:404}));await eraseRevenueCatCustomer(db,id,job,claim);expect(fetcher.mock.calls[2][0]).toContain('/aliases?limit=100&starting_after=opaque%2Fid');expect(fetcher.mock.calls.every(call=>String(call[0]).startsWith('https://api.revenuecat.com/'))).toBe(true);});
});
